WeBankPartners/we-cmdb

cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java
=> #218 fix mult selection issue

cmdb-core/database/data_model.sql, cmdb-core/src/main/java/com/webank/cmdb/domain/AdmCiTypeAttr.java, cmdb-core/src/main/java/com/webank/cmdb/dto/CiTypeAttrDto.java, cmdb-core/src/test/resources/db/data_model.sql, cmdb-core/src/test/resources/db/legacy/1.init.schema.sql, cmdb-ui/src/pages/admin/cmdb-model-management.vue, cmdb-ui/src/pages/components/table.js
hold my emoji pleas @irvinezhao
=> 34 ci attr support regular expression rule

cmdb-core/src/main/java/com/webank/cmdb/controller/ui/UIUserManagementController.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIUserManagerService.java, cmdb-core/src/main/java/com/webank/cmdb/domain/AdmUser.java
#196 Canonical  naming for variable 、 API,Bug fix
=> #196 Canonical  naming for variable 、 API,Bug fix

cmdb-ui/src/pages/admin/permission-management.vue, cmdb-ui/src/pages/designing/application-architecture.vue, cmdb-ui/src/pages/designing/application-deployment.vue, cmdb-ui/src/pages/designing/physical-graph.vue, cmdb-ui/src/pages/designing/planning.vue, cmdb-ui/src/pages/designing/resource-planning.vue
#292 physical graph page title
#293 physical graph page can not show graph
#299 physical graph page color optimization
=> :bug: #292 #293 #299 fixed physical graph page bugs

cmdb-wiki/docs/developer/code_contributors_submit_guide_en.md, cmdb-wiki/docs/developer/eclipse_install_guide_en.md, cmdb-wiki/docs/developer/jdk_install_guide_en.md, cmdb-wiki/docs/developer/mysql_install_guide_en.md, cmdb-wiki/docs/developer/wecmdb_developer_guide_en.md, cmdb-wiki/docs/developer/wecmdb_local_standalone_guide_en.md, cmdb-wiki/docs/install/docker-compose_install_guide_en.md, cmdb-wiki/docs/install/docker_install_guide_en.md, cmdb-wiki/docs/install/git_install_guide_en.md, cmdb-wiki/docs/install/wecmdb_compile_guide_en.md, cmdb-wiki/docs/install/wecmdb_install_guide_en.md
update #357 #313 #312 #309 #308
=> Update en docs

cmdb-core/src/main/java/com/webank/cmdb/repository/AdmMenusRepository.java
Login with code and query with name, so users with different code and name have no permission
=> #321 New user has no permissions

cmdb-core/src/main/resources/database/ch/02.cmdb.system.data_ch.sql, cmdb-core/src/main/resources/database/ch/03.cmdb.system.data.mysql_ch.sql, cmdb-core/src/main/resources/database/en/02.cmdb.system.data_en.sql, cmdb-core/src/main/resources/local/ch/03.cmdb.system.data.h2_ch.sql
=> #426 Change the init CI type attrs to notCreate

cmdb-wiki/docs/api/wecmdb_api_guide.md
Perfect api guide for user、role、role-user、permission-role(menuPermission、CIt ype Permission)
=> #314 Perfect api guide

cmdb-core/src/main/java/com/webank/cmdb/service/impl/DatabaseServiceImpl.java
H2 database SQL performs error fixes
=> Database compatibility repair

cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java, cmdb-core/src/test/java/com/webank/cmdb/controller/apiv2/ApiV2ControllerCiDataTest.java
Hi Reviewers,
The PR here is to address the default value when the target value is absent for auto fill.
After changed, the default value is blank "" now.
Regards,
Jordan.
=> #537 Adjust the default value to blank instead of guid

cmdb-plugin/register.xml, cmdb-ui/src/api/server.js, cmdb-ui/src/locale/i18n/en-US.json, cmdb-ui/src/locale/i18n/zh-CN.json, cmdb-ui/src/pages/admin/cmdb-model-management.vue, cmdb-ui/src/pages/admin/plugin-permission-management.vue, cmdb-ui/src/router-plugin.js
#559 WeCMDB插件化权限管理菜单缺失
wecmdb作为wecube插件时，新增一个页面，“cmdb权限控制”。
=> :sparkles: #559 add new page: CMDB Permission for wecube's plugin

cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java
Fixed an issue where p_guid was empty when modifying ci data
=> #576 Fix p_guid was empty when modifying ci data

cmdb-core/src/main/java/com/webank/cmdb/controller/ApiV2Controller.java
#539 Add the interface for get special connector to artifacts
=> #539 Add the interface for get special connector

cmdb-ui/src/pages/components/auto-fill.js, cmdb-ui/src/pages/components/sequence-diagram.vue, cmdb-ui/src/pages/designing/application-architecture.vue
#561 WeCMDB应用架构设计支持历史版本查询
- 第五点 去定版 按钮点击后，只返回该系统设计下，未定版的数据（完成）
#597 交易时序图 - 适应新模型（已完成）
=> :bug: #561 fixed bug: App Logical Diagram bugs

cmdb-core/src/main/java/com/webank/cmdb/service/impl/FilterRuleService.java, cmdb-ui/src/pages/designing/application-architecture.vue, cmdb-ui/src/pages/designing/physical-graph.vue
=> 561 app design graph bugs

cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java
#561 Fix the APP deploy dessign query
=> #561 Fix the APP deploy dessign query

cmdb-ui/src/pages/designing/ci-data.vue
修复了CI数据查询及CI数据管理页面中，重置查询条件后仍然返回带有查询条件的结果的bug
=> :bug: #593 fixed bug: can not reset filter when ci data enquire

cmdb-plugin/register.xml, cmdb-ui/src/pages/components/ci-graph.js, cmdb-ui/src/pages/designing/application-architecture.vue, cmdb-ui/src/pages/designing/application-deployment.vue, cmdb-ui/src/pages/designing/planning.vue, cmdb-ui/src/pages/designing/resource-planning.vue
1、修改了 **机房规划设计** 、 **机房资源规划**、**应用架构设计**、**应用部署设计** 页面中，ci表格多选枚举显示错误的问题；
2、修改了register.xml默认IP的，现使用本机IP；
3、综合查询页面，弹框不再记录上次的tab
=> 678 cmdb table cell type bug

cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/service/WecubeAdapterService.java
=> Fix the comfirm state code

cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIUserManagerService.java, cmdb-core/src/main/java/com/webank/cmdb/dto/UserAndPasswordDto.java
Fix wrongpassword when user changes password
=> #670 Fix wrong password when user changes password

cmdb-core/src/main/java/com/webank/cmdb/controller/ui/UICiDataManagementController.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java, cmdb-ui/src/api/server.js, cmdb-ui/src/pages/designing/application-architecture.vue
Fix app architecture designs hsitory data
=> #696 fix app architecture designs hsitory data

cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java
When the CI attribute state is notCreated, no validation is performed
=> #704 Add the state judgement

cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java, cmdb-ui/src/const/actions.js, cmdb-ui/src/pages/admin/cmdb-model-management.vue, cmdb-ui/src/pages/admin/components/enum-group-modal.vue, cmdb-ui/src/pages/admin/enums.vue, cmdb-ui/src/pages/admin/permission-management.vue, cmdb-ui/src/pages/admin/plugin-permission-management.vue, cmdb-ui/src/pages/change-password.vue, cmdb-ui/src/pages/components/auto-fill.js, cmdb-ui/src/pages/components/table.js, cmdb-ui/src/pages/designing/application-architecture.vue, cmdb-ui/src/pages/designing/application-deployment.vue, cmdb-ui/src/pages/designing/ci-data.vue, cmdb-ui/src/pages/designing/ci-integrated-query-management.vue, cmdb-ui/src/pages/designing/planning.vue, cmdb-ui/src/pages/designing/resource-planning.vue, cmdb-ui/src/pages/util/state-operations.js
1、排查了页面中的所有按钮，为所有需要调后台接口的按钮增加了loading，防止二次点击，除此之外，一些需要loading的其他组件也增加了loading #692
2、模型管理页面右侧表单项之间的间距缩小，以便展示更多内容 #702
3、修复了一些在过程中发现的bug
=> 692 async button loading

cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiTypeInterceptorService.java, cmdb-ui/src/locale/i18n/en-US.json, cmdb-ui/src/locale/i18n/zh-CN.json, cmdb-ui/src/pages/admin/cmdb-model-management.vue
=> 712 ci model graph add layers

Dockerfile, cmdb-plugin/Dockerfile, cmdb-plugin/pom.xml, cmdb-plugin/register.xml, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/controller/WecubeAdapterController.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/dto/wecube/Filter.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/dto/wecube/QueryRequest.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/helper/HttpUtils.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/service/WecubeAdapterService.java
=> 703 pluging support filter query

cmdb-core/src/main/java/com/webank/cmdb/repository/AdmCiTypeAttrRepository.java, cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java
#749 Fix the Auto fill for state
=> #749 Fix the Auto fill for state

cmdb-core/src/main/java/com/webank/cmdb/config/ApplicationProperties.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java
=> # 712 Modeify the citype id for properties

cmdb-core/src/main/java/com/webank/cmdb/config/ApplicationProperties.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java
init the view ci type id form database
=> init the view ci type id form database

cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/service/WecubeAdapterService.java
Modify the plugin retrieveCiData response --displayName code to key_name
=> Modify the plugin retrieveCiData response --displayName code to key_name

cmdb-core/src/main/java/com/webank/cmdb/repository/impl/StaticEntityRepositoryImpl.java
=> table name case-sensitive

cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java, cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java, cmdb-plugin/register.xml
#776 #768 fix the auto fill for state code and modify the db time zone
=> #776 #768 fix the auto fill for state code and modify the db time zone

cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java
Fix the error for query view tabs
=> Fix the error for query view tabs

cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java, cmdb-core/src/main/java/com/webank/cmdb/service/impl/FilterRuleService.java, cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java
#803 Fix the error for Not an entity
=> #803 Fix the error for Not an entity

cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java
#795 fix the delete cidata failed
=> #795 fix the delete cidata failed

cmdb-core/src/main/java/com/webank/cmdb/stateTransition/ConfirmAction.java, cmdb-core/src/main/resources/application.yml, cmdb-plugin/scripts/start.sh
Fixed #768, fix timezone issue
=> #768 - Fixed #768, fix timezone issue

cmdb-ui/src/App.vue, cmdb-ui/src/pages/admin/cmdb-model-management.vue, cmdb-ui/src/pages/components/table.js, cmdb-ui/src/pages/designing/application-architecture.vue, cmdb-ui/src/pages/designing/application-deployment.vue, cmdb-ui/src/pages/designing/ci-data.vue, cmdb-ui/src/pages/designing/planning.vue, cmdb-ui/src/pages/designing/resource-planning.vue, cmdb-ui/src/pages/home-page.vue
#724 fixed bug: not required attribute remove asterisk
#814 fixed bug: new CI data error
=> :bug: #724 #814

cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java, cmdb-core/src/test/java/com/webank/cmdb/service/CiServiceImplLegacyModelTest.java, cmdb-core/src/test/resources/db/legacy/3.init.static.data.ci.sql
#813 modify the fix date to null when create cidata
=> #813 modify the fix date to null when create cidata

cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java
#734 don`t validate when value is null and value can be null
=> #734 don`t validate when value is null and value can be null

cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/service/WecubeAdapterService.java
Modify error code success when guid is ""
=> Modify error code success when guid is ""

cmdb-core/src/main/resources/application.yml, cmdb-core/src/main/resources/database/ch/01.cmdb.schema_ch.sql, pom.xml
=> Sql adapter h2base

Dockerfile, cmdb-plugin/Dockerfile
Update the cmdb vertion to 1.4.3 for DockerFile
=> Update the cmdb vertion to 1.4.3 for DockerFile

cmdb-core/src/main/java/com/webank/cmdb/constant/FilterOperator.java, cmdb-core/src/main/java/com/webank/cmdb/util/JpaQueryUtils.java
=> #954 Support like query

cmdb-core/src/database/delta/964_ref_delete_validate.sql, cmdb-core/src/main/java/com/webank/cmdb/domain/AdmCiTypeAttr.java, cmdb-core/src/main/java/com/webank/cmdb/dto/CiTypeAttrDto.java, cmdb-core/src/main/java/com/webank/cmdb/repository/AdmCiTypeAttrRepository.java, cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java, cmdb-core/src/test/java/com/webank/cmdb/controller/apiv2/ApiV2ControllerCiDataTest.java, cmdb-core/src/test/resources/db/data_model.sql, cmdb-core/src/test/resources/db/legacy/1.init.schema.sql, cmdb-core/src/test/resources/db/legacy/3.init.static.data.ci.sql, cmdb-ui/src/locale/i18n/en-US.json, cmdb-ui/src/locale/i18n/zh-CN.json, cmdb-ui/src/pages/admin/cmdb-model-management.vue
=> 964 remove validate

cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java, cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java
=> #1005 fixed query architecture data exception

cmdb-plugin/register.xml
=> add platform requirement

README.md, README_EN.md
This reverts commit d1ff812a99538890809b059bb0d99a88cd4386bc.
=> Revert "update readme" to bring back demo link

cmdb-core/src/main/java/com/webank/cmdb/authclient/filter/JwtSsoBasedAuthenticationFilter.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ApiV2Controller.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/UICiDataManagementController.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/UIFileManagementController.java, cmdb-core/src/main/java/com/webank/cmdb/controller/ui/helper/UIWrapperService.java, cmdb-core/src/main/java/com/webank/cmdb/dynamicEntity/DynamicEntityHolder.java, cmdb-core/src/main/java/com/webank/cmdb/expression/RouteQueryExpressionListener.java, cmdb-core/src/main/java/com/webank/cmdb/repository/impl/StaticEntityRepositoryImpl.java, cmdb-core/src/main/java/com/webank/cmdb/service/impl/CiServiceImpl.java, cmdb-core/src/main/java/com/webank/cmdb/service/impl/StaticDtoServiceImpl.java, cmdb-core/src/main/java/com/webank/cmdb/service/interceptor/CiDataInterceptorService.java, cmdb-core/src/main/java/com/webank/cmdb/support/mvc/ResponseResultProcess.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/propenc/RsaBasedStringEncryptor.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/propenc/RsaEncryptor.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/propenc/RsaKeyDetector.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/service/WecubeAdapterService.java
=> Exception handling refactor

cmdb-core/src/main/java/com/webank/cmdb/dto/QueryResponse.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/dto/wecube/AttributeDto.java, cmdb-plugin/src/main/java/com/webank/plugins/wecmdb/service/WecubeAdapterService.java, cmdb-plugin/src/test/java/com/webank/plugins/wecmdb/controller/WeCubeDataModelApiControllerTest.java
This reverts commit 80ba924aa353cc4d4f71d35f225a1dddb940605c.
=> Revert "add nullable and editable for data model attributes"
